title: Featurebase help
description: FeatureBase enables data engineers to process and operate on massive, continuously changing datasets in real time.
theme: just-the-docs

url: https://github.com/FeatureBaseDB/featurebase-docs
# remote_theme: "pmarsceill/just-the-docs"
# url: https://just-the-docs.github.io

# External navigation links appear in the sidebar navigation right at the bottom
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs
#    hide_icon: false # set to true to hide the external link icon - defaults to false

# Exclude folders from build
exclude: [/help-on-help]

# Top of page nav
  # Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
  # Anchor text and hyperlinks that appear in top of page nav
aux_links:
  Featurebase home: https://featurebase.com
  API docs: https://api-docs-featurebase-cloud.redoc.ly/
  Contact us: https://www.featurebase.com/contact-us

# permalink info found on https://jekyllrb.com/docs/permalinks/
# WARNING: SITE LINKS WILL BREAK IF THIS IS CHANGED FROM `pretty`
permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/FeatureBase-Logo-Gradient-Wide.png"

color_scheme: featurebase # file URL: /_sass/color_schemes/featurebase.css

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Maximum amount of previews per search result
# Default: 3
search.previews: 10

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Text highlighting callouts

  # Colours found in /_sass/color_schemes for red, green, purple. other colors are theme defaults

callouts_level: loud # or quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  success:
    title: Success
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
