version: '3'

services:
  serve:
    build: .
    image: serve-jeckyll-docs-fb
    container_name: featurebase-docs-site-container
    command: jekyll serve --watch --force_polling --verbose --livereload
    volumes:
      - .:/srv/jekyll:consistent
    ports:
      - '4000:4000'
    expose:
      - '4000'
